### ISSUE TITLE
error:with the asm method, the constant value has to be of type uint64 , couldn't edit target_port in egress_cls_func

### ISSUE THREAD

**Issue by SeeFlowerX** [ehids/ecapture#166]
**Describe the bug**

**Pixel6**上配置安卓chroot环境（debian arm64）编译的最新版ecapture

系统的头文件在`/sys/kernel/kheaders.tar.xz`，如下（下载后请去掉.zip后缀解压）

[kheaders.tar.xz.zip](https://github.com/ehids/ecapture/files/9286390/kheaders.tar.xz.zip)

内核版本是`Linux localhost 5.10.43-android12-9-00007-g9771767708df-ab8009062 #1 SMP PREEMPT Thu Dec 16 04:22:18 UTC 2021 aarch64`

**To Reproduce**

执行以下命令时报错

```bash
./ecapture tls -i wlan0 -u 10224 --debug true --libssl /apex/com.android.conscrypt/lib64/libssl.so --pthread /apex/com.android.runtime/lib64/bionic/libc.so --write test.pcap
```

```log
2022/08/09 02:46:06 Your environment is a container. We will not detect the BTF config.
tls_2022/08/09 02:46:06 ECAPTURE :: pid info :17105
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        module initialization
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        module started successfully.
tls_2022/08/09 02:46:06 EBPFProbeGNUTLS module initialization failed. [skip it]. error:stat /usr/lib/libgnutls.so.30: no such file or directory
tls_2022/08/09 02:46:06 EBPFProbeNSPR   module initialization failed. [skip it]. error:stat /usr/lib/libnspr4.so: no such file or directory
tls_2022/08/09 02:46:06 EBPFProbeGoSSL  module [disabled].
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        Module.Run()
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        TC MODEL
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        Ifname:wlan0, Ifindex:47,  Port:443, Pcapng filepath:/data/local/tmp/test.pcap
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        target all process.
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        target UID:10224
tls_2022/08/09 02:46:06 EBPFProbeOPENSSL        module run failed, [skip it]. error:couldn't init manager error:with the asm method, the constant value has to be of type uint64 , couldn't edit target_port in egress_cls_func
^Ctls_2022/08/09 02:46:16 EBPFProbeOPENSSL      saving pcapng file /data/local/tmp/test.pcap
tls_2022/08/09 02:46:16 EBPFProbeOPENSSL         save 0 packets into pcapng file.
tls_2022/08/09 02:46:16 EBPFProbeOPENSSL        close.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x243200]

goroutine 1 [running]:
github.com/cilium/ebpf.(*Collection).Close(0x0)
        /root/go/pkg/mod/github.com/cilium/ebpf@v0.9.0/collection.go:616 +0x20
github.com/ehids/ebpfmanager.(*Manager).stop(0x4000082d00, 0x3e)
        /root/go/pkg/mod/github.com/ehids/ebpfmanager@v0.3.0/manager.go:666 +0x524
github.com/ehids/ebpfmanager.(*Manager).Stop(0x4000082d00, 0x3e)
        /root/go/pkg/mod/github.com/ehids/ebpfmanager@v0.3.0/manager.go:624 +0xfc
ecapture/user.(*MOpenSSLProbe).Close(0x4000169400)
        /ecapture/user/probe_openssl.go:193 +0x158
ecapture/cli/cmd.openSSLCommandFunc(0x87c5e0, {0x4000320240, 0x1, 0xc})
        /ecapture/cli/cmd/tls.go:156 +0xc20
github.com/spf13/cobra.(*Command).execute(0x87c5e0, {0x4000320180, 0xc, 0xc})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x650
github.com/spf13/cobra.(*Command).ExecuteC(0x87c360)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x424
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
ecapture/cli/cmd.Execute()
        /ecapture/cli/cmd/root.go:60 +0x154
ecapture/cli.Start(...)
        /ecapture/cli/main.go:12
main.main()
        /ecapture/main.go:63 +0x2e4
```

**Linux Server/Android (please complete the following information):**

- OS: Android
- Arch: aarch64
- Kernel Version: 5.10.43
- Version: SQ1D.220205.004

**Comment by SeeFlowerX** [comment]
把下面的这行的uint32改为uint64即可

- https://github.com/ehids/ecapture/blob/b28ab315c0dbab8273607922173b17aea1963bf2/user/probe_openssl.go#L213

不过抓包结果似乎有些异常

![image](https://user-images.githubusercontent.com/70688581/183554996-43deee8a-6d44-47fc-ae8f-8d2c1d7c25c3.png)

**Comment by cfc4n** [comment]
dup : https://github.com/ehids/ecapture/issues/156

**Comment by cfc4n** [comment]
## 文本输出格式
`./ecapture tls `

## pcapng格式
`./ecapture tls -i wlan0 -w t.pcapng`

文本输出格式应该可以。  pcapng格式是因为Android的openssl版本部署i通用的，offset不一样，需要重新定位。

**Comment by SeeFlowerX** [comment]
了解了
